title: Homebrew
description: The missing package manager for macOS.

exclude:
  - bin
  - CNAME
  - Gemfile*
  - Rakefile
  - README.md
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: atom.xml

permalink: /:categories/:year/:month/:day/:title

defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: :year/:month/:day/:title/
  - scope:
      path: ""
    values:
      image: /images/apple-touch-icon.png

logo: /images/apple-touch-icon.png

github:
  repository_nwo: Homebrew/homebrew.github.io

twitter:
  username: MacHomebrew

facebook:
  publisher: https://www.facebook.com/machomebrew/
