name: Homebrew
description: The missing package manager for macOS.

# Same as GitHub Pages
# https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
# Disable despite enabled on GitHub Pages for supported plugins to work.
# safe: true
kramdown:
  input: GFM
  hard_wrap: false
lsi: false
highlighter: rouge

include:
  - _headers

exclude:
  - bin
  - CNAME
  - Gemfile*
  - Rakefile
  - README.md
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: atom.xml

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      permalink: ":year/:month/:day/:title/"
