name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Install Ruby
        uses: ruby/setup-ruby@ff740bc00a01b3a50fffc55a1071b1060eeae9dc # v1.180.0
        with:
          bundler-cache: true

      - name: Run HTML Proofer tests
        run: bundle exec rake test

  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install vale
        run: brew install vale

      - name: Run Vale linting on Markdown files
        run: vale --config=$(brew --repo)/.vale.ini _posts/

  check-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Check release notes redirect
        run: ruby ./.github/actions/check-redirects.rb
