name: CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@main

    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: 2.6

    - name: Install RubyGems
      run: |
        gem install bundler -v "~>1"
        bundle install --jobs 4 --retry 3

    - name: Run HTML Proofer tests
      run: bundle exec rake test

  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Run Vale linting on Markdown files
        run: |
          brew install vale
          vale --config=$(brew --repo)/.vale.ini _posts/

  check-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Check release notes redirect
        run: ruby ./.github/actions/check-redirects.rb
